/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_badlogic_gdx_jnigen_JniGenTestClass_TestInner */

#ifndef _Included_com_badlogic_gdx_jnigen_JniGenTestClass_TestInner
#define _Included_com_badlogic_gdx_jnigen_JniGenTestClass_TestInner
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_badlogic_gdx_jnigen_JniGenTestClass_TestInner
 * Method:    testInner
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_badlogic_gdx_jnigen_JniGenTestClass_00024TestInner_testInner
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
