/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_badlogic_gdx_jnigen_JniGenTestClass */

#ifndef _Included_com_badlogic_gdx_jnigen_JniGenTestClass
#define _Included_com_badlogic_gdx_jnigen_JniGenTestClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_badlogic_gdx_jnigen_JniGenTestClass
 * Method:    testBoolean
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_badlogic_gdx_jnigen_JniGenTestClass_testBoolean
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_badlogic_gdx_jnigen_JniGenTestClass
 * Method:    testByte
 * Signature: (B)B
 */
JNIEXPORT jbyte JNICALL Java_com_badlogic_gdx_jnigen_JniGenTestClass_testByte
  (JNIEnv *, jclass, jbyte);

/*
 * Class:     com_badlogic_gdx_jnigen_JniGenTestClass
 * Method:    testChar
 * Signature: (C)C
 */
JNIEXPORT jchar JNICALL Java_com_badlogic_gdx_jnigen_JniGenTestClass_testChar
  (JNIEnv *, jclass, jchar);

/*
 * Class:     com_badlogic_gdx_jnigen_JniGenTestClass
 * Method:    testShort
 * Signature: (S)S
 */
JNIEXPORT jshort JNICALL Java_com_badlogic_gdx_jnigen_JniGenTestClass_testShort
  (JNIEnv *, jclass, jshort);

/*
 * Class:     com_badlogic_gdx_jnigen_JniGenTestClass
 * Method:    testInt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_badlogic_gdx_jnigen_JniGenTestClass_testInt
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_badlogic_gdx_jnigen_JniGenTestClass
 * Method:    testLong
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_badlogic_gdx_jnigen_JniGenTestClass_testLong
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_badlogic_gdx_jnigen_JniGenTestClass
 * Method:    testFloat
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_com_badlogic_gdx_jnigen_JniGenTestClass_testFloat
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     com_badlogic_gdx_jnigen_JniGenTestClass
 * Method:    testDouble
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_com_badlogic_gdx_jnigen_JniGenTestClass_testDouble
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     com_badlogic_gdx_jnigen_JniGenTestClass
 * Method:    test
 * Signature: (ZBCSIJFDLjava/nio/Buffer;[Z[C[S[I[J[F[D[[DLjava/lang/String;Ljava/lang/Class;Ljava/lang/Throwable;Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_badlogic_gdx_jnigen_JniGenTestClass_test
  (JNIEnv *, jclass, jboolean, jbyte, jchar, jshort, jint, jlong, jfloat, jdouble, jobject, jbooleanArray, jcharArray, jshortArray, jintArray, jlongArray, jfloatArray, jdoubleArray, jobjectArray, jstring, jclass, jthrowable, jobject);

#ifdef __cplusplus
}
#endif
#endif
